---
title: "CPF2976Exception class | QSYS API Reference Guide"
description: "The exception that is thrown when Number of errors greater than ERRLVL value. "
last_modified_at: 2024-07-09T17:00:49Z
---

The exception that is thrown when Number of errors greater than ERRLVL value.

**Namespace:** ASNA.QSys.Runtime.JobSupport
**Assembly:** ASNA.QSys.Runtime.dll

**Inheritance:** [Object](https://docs.microsoft.com/en-us/dotnet/api/system.object) --> [Exception](https://docs.microsoft.com/en-us/dotnet/api/system.exception) --> [JobException](/reference/runtime/qsys-runtime-job-support/job-exception.html) --> [CPF0000Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf0000-exception.html) --> [CPF2900Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2900-exception.html)
<br>
<br>

## Constructors

| Name | Description |
| --- | --- |
| [CPF2976Exception](#cpf2976exceptionexception)([Exception](https://docs.microsoft.com/en-us/dotnet/api/system.exception)) | Initializes a new instance of the CPF2976Exception class.

### CPF2976Exception([Exception](https://docs.microsoft.com/en-us/dotnet/api/system.exception))

Initializes a new instance of the CPF2976Exception class.

```cs
CPF2976Exception(Exception)
```

#### Parameters

| Type | Parameter name | Description
| --- | --- | ---
| [Exception](https://docs.microsoft.com/en-us/dotnet/api/system.exception) | innerException | The exception that is the cause of the current exception, or a null reference if no inner exception is specified.
